management:
  endpoints.web:
    exposure.include: health, prometheus
    path-mapping:
      prometheus: /metrics
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
  profiles.active: ${SPRING_PROFILE:local}
